
have_board imx8mmq_compulab_iot_gateway
assert_spec arm_v8a

create_boot_directory
import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/base-hw-imx8mmq_compulab_iot_gateway_drivers \
                  [depot_user]/src/init \
                  [depot_user]/src/platform_drv \
                  [depot_user]/src/usdhc \
                  [depot_user]/src/report_rom

build { app/block_tester }

install_config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default caps="100"/>

	<start name="imx8mq_platform_drv">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Platform"/></provides>
		<config>

			<device name="usdhc2" type="fsl,imx7d-usdhc">
				<io_mem address="0x30b50000" size="0x10000"/>
				<irq    number="55"/>
				<clock  name="ipg_clk_root"
				        driver_name="ipg"/>
				<clock  name="nand_usdhc_bus_clk_root"
				        driver_name="ahb"/>
				<clock  name="usdhc2_clk_root"
				        rate="200000000"
				        driver_name="per"/>
				<clock  name="usdhc2_gate"/>
			</device>

			<policy label="imx_usdhc_drv -> " info="yes">
				<device name="usdhc2"/>
			</policy>

			<device name="gpio-bank_1">
				<io_mem address="0x30200000" size="0x10000"/>
				<irq number="96"/>
				<irq number="97"/>
			</device>

			<policy label="regulator-usdhc2_v -> " info="yes">
				<device name="gpio-bank_1"/>
			</policy>

			<device name="gpio-bank_2">
				<io_mem address="0x30210000" size="0x10000"/>
				<irq number="98"/>
				<irq number="99"/>
			</device>

			<policy label="regulator-usdhc2_rst -> " info="yes">
				<device name="gpio-bank_2"/>
			</policy>

		</config>
		<route>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
		<route> <any-service> <parent/> </any-service> </route>
	</start>

	<start name="report_rom">
		<resource name="RAM" quantum="2M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="yes">
		</config>
		<route> <any-service> <parent/> </any-service> </route>
	</start>

	<start name="regulator-usdhc2_v" caps="300">
		<binary name="imx_gpio_drv"/>
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Gpio"/></provides>
		<config>
			<gpio num="4" mode="O" value="1"/>
		</config>

		<route>
			<service name="Platform"> <child name="imx8mq_platform_drv"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="regulator-usdhc2_rst" caps="300">
		<binary name="imx_gpio_drv"/>
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Gpio"/></provides>
		<config>
			<gpio num="19" mode="O" value="1"/>
		</config>

		<route>
			<service name="Platform"> <child name="imx8mq_platform_drv"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="imx_usdhc_drv" caps="300">
		<resource name="RAM" quantum="16M"/>
		<provides><service name="Block"/></provides>
		<config report="yes">
			<default-policy device="mmcblk0"/>
		</config>
		<route>
			<service name="ROM" label="dtb">
				<parent label="imx_usdhc_drv-imx8mmq_compulab_iot_gateway.dtb"/>
			</service>
			<service name="ROM"> <parent/> </service>
			<service name="PD">  <parent/> </service>
			<service name="RM">  <parent/> </service>
			<service name="CPU"> <parent/> </service>
			<service name="LOG"> <parent/> </service>
			<any-service> <any-child/> </any-service>
		</route>
	</start>

	<start name="block_tester">
		<resource name="RAM" quantum="64M" />
		<config verbose="no" report="no" log="yes" stop_on_error="no">
			<tests>
				<sequential write="no" length="256M" size="1M" io_buffer="8M" batch="4"/>
				<random write="no" length="512M" size="512K" seed="0xc0ffee" />
			</tests>
		</config>
		<route>
			<service name="ROM"> <parent/> </service>
			<service name="PD">  <parent/> </service>
			<service name="RM">  <parent/> </service>
			<service name="CPU"> <parent/> </service>
			<service name="LOG"> <parent/> </service>
			<any-service> <any-child/> </any-service>
		</route>
	</start>
</config>
}

build_boot_image {
	block_tester
	imx_usdhc_drv-imx8mmq_compulab_iot_gateway.dtb
}

run_genode_until "child \"block_tester\" exited with exit value 0" 180
